[CmdletBinding()]
param([Parameter(Mandatory=$true)][ValidateSet('Prepare','Restore')][string]$Action,[string]$BackupDirectory,[string]$SyntheticFixtureRoot,[switch]$SimulateReceiptFailure)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'; $markerName='.isrworldgen-l00c-mount.json'
function Get-CanonicalPath([string]$Path){[IO.Path]::GetFullPath((Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path)}
function Assert-ChildPath([string]$Child,[string]$Parent,[string]$Label){$prefix=$Parent.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;if(-not $Child.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Label must stay below $Parent."}}
function Get-Sha256([byte[]]$Bytes){$algorithm=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($algorithm.ComputeHash($Bytes))).Replace('-','')}finally{$algorithm.Dispose()}}
function Get-TreeHash([string]$Root){$rows=foreach($item in @(Get-ChildItem -LiteralPath $Root -File -Recurse|Sort-Object FullName)){$relative=$item.FullName.Substring($Root.TrimEnd([IO.Path]::DirectorySeparatorChar).Length).TrimStart([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);if($relative -ne $markerName){"$relative|$($item.Length)|$(Get-Sha256 ([IO.File]::ReadAllBytes($item.FullName)))"}};Get-Sha256 ([Text.Encoding]::UTF8.GetBytes(($rows -join "`n")))}
function Test-Sha256([object]$Value){$null -ne $Value -and ([string]$Value -match '^[0-9A-F]{64}$')}
function Write-NewUtf8([string]$Path,[string]$Content){$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$bytes=[Text.UTF8Encoding]::new($false).GetBytes($Content);$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}
function Replace-Utf8Atomically([string]$Path,[string]$Content){$temporary="$Path.$([Guid]::NewGuid().ToString('N')).tmp";try{Write-NewUtf8 $temporary $Content;Move-Item -LiteralPath $temporary -Destination $Path -Force}finally{if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Force}}}
if($SyntheticFixtureRoot){$repository=Get-CanonicalPath $SyntheticFixtureRoot;Assert-ChildPath $repository ([IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd([IO.Path]::DirectorySeparatorChar)) 'Synthetic fixture root'}else{$repository=Get-CanonicalPath (Join-Path $PSScriptRoot '..\..\..')}
$laboratory=Get-CanonicalPath (Join-Path $repository '.local\L00C');$sourceCandidate=Join-Path $laboratory 'menu-action-testmod\Debug\isrworldgenl00clab';$source=if(Test-Path -LiteralPath $sourceCandidate){Get-CanonicalPath $sourceCandidate}else{[IO.Path]::GetFullPath($sourceCandidate)};$modsRoot=Get-CanonicalPath (Join-Path $repository 'src\WorldGen.VintageStory\bin\Debug\Mods');$mountedPackage=Join-Path $modsRoot 'isrworldgenl00clab';$backupParent=Join-Path $laboratory 'mount-backups'
if($Action -eq 'Restore'){
 if([string]::IsNullOrWhiteSpace($BackupDirectory)){throw 'Restore requires -BackupDirectory returned by Prepare.'};$backup=Get-CanonicalPath $BackupDirectory;Assert-ChildPath $backup $backupParent 'Mount backup directory';$receiptPath=Join-Path $backup 'metadata.json';if(-not(Test-Path -LiteralPath $receiptPath -PathType Leaf)){throw 'Mount receipt is incomplete.'};$receipt=Get-Content -LiteralPath $receiptPath -Raw|ConvertFrom-Json
 if($receipt.Owner -ne (Get-Acl -LiteralPath $backup).Owner -or $receipt.SourcePackage -ne $source -or $receipt.ModsRoot -ne $modsRoot -or $receipt.MountedPackage -ne $mountedPackage -or [string]::IsNullOrWhiteSpace($receipt.MountId) -or -not(Test-Sha256 $receipt.SourceTreeSha256) -or -not(Test-Sha256 $receipt.MountedTreeSha256)){throw 'Mount receipt identity or SHA-256 provenance is not trusted for this exact destination.'};if((Test-Path -LiteralPath $source -PathType Container) -and (Get-TreeHash $source) -ne $receipt.SourceTreeSha256){throw 'Current L00-C source package no longer matches the mount receipt.'};if(-not(Test-Path -LiteralPath $mountedPackage -PathType Container)){throw 'Mounted L00-C package is absent; refusing to remove or recreate anything.'};$markerPath=Join-Path $mountedPackage $markerName;$markerLock=[IO.File]::Open($markerPath,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)
 try{$marker=[Text.UTF8Encoding]::new($false).GetString(([IO.File]::ReadAllBytes($markerPath)))|ConvertFrom-Json;if(-not(Test-Sha256 $marker.SourceTreeSha256) -or -not(Test-Sha256 $marker.MountedTreeSha256) -or $marker.MountId -ne $receipt.MountId -or $marker.MountedPackage -ne $mountedPackage -or $marker.SourceTreeSha256 -ne $receipt.SourceTreeSha256 -or $marker.MountedTreeSha256 -ne $receipt.MountedTreeSha256 -or (Get-TreeHash $mountedPackage) -ne $receipt.MountedTreeSha256){throw 'Mounted package does not match its trusted receipt and atomic provenance marker.'};$markerLock.Dispose();$markerLock=$null;Remove-Item -LiteralPath $mountedPackage -Recurse -Force}finally{if($null -ne $markerLock){$markerLock.Dispose()}};if(Test-Path -LiteralPath $mountedPackage){throw 'Mounted L00-C package cleanup verification failed.'};[ordered]@{Status='RESTORED';BackupDirectory=$backup;MountedPackage=$mountedPackage}|ConvertTo-Json -Compress;return
}
foreach($required in @($laboratory,(Join-Path $laboratory '.isrworldgen-lab'),$source,(Join-Path $source 'modinfo.json'),(Join-Path $source 'ISRWorldGen.L00C.MenuActionLab.dll'))){if(-not(Test-Path -LiteralPath $required)){throw "Required L00-C mount input is missing: $required"}};if(-not(Test-Path -LiteralPath $modsRoot -PathType Container)){throw "The existing production F5 Mods parent is required: $modsRoot"};if(Test-Path -LiteralPath $mountedPackage){throw "Refusing to overwrite existing production Mods child: $mountedPackage"}
$mountId=[Guid]::NewGuid().ToString('N');$sourceTreeSha256=Get-TreeHash $source;$staging=Join-Path $modsRoot ('.l00c-stage-'+$mountId);$backup=$null;$moved=$false
try{Copy-Item -LiteralPath $source -Destination $staging -Recurse -ErrorAction Stop;if((Get-TreeHash $staging) -ne $sourceTreeSha256){throw 'Staged L00-C package hash does not match its source package.'};$mountedTreeSha256=$sourceTreeSha256;$marker=[ordered]@{MountId=$mountId;MountedPackage=$mountedPackage;SourceTreeSha256=$sourceTreeSha256;MountedTreeSha256=$mountedTreeSha256};Write-NewUtf8 (Join-Path $staging $markerName) ($marker|ConvertTo-Json -Compress);if((Get-TreeHash $staging) -ne $mountedTreeSha256){throw 'Normalized mounted tree hash does not match its source package.'};[void](New-Item -ItemType Directory -Path $backupParent -Force);$backup=Join-Path $backupParent ('mount-'+$mountId);[void](New-Item -ItemType Directory -Path $backup -ErrorAction Stop);if($SimulateReceiptFailure){throw 'Simulated receipt persistence failure.'};$receipt=[ordered]@{Owner=(Get-Acl -LiteralPath $backup).Owner;MountId=$mountId;SourcePackage=$source;ModsRoot=$modsRoot;MountedPackage=$mountedPackage;SourceTreeSha256=$sourceTreeSha256;MountedTreeSha256=$mountedTreeSha256;State='STAGED';PreparedUtc=[DateTimeOffset]::UtcNow.ToString('o')};$receiptPath=Join-Path $backup 'metadata.json';Write-NewUtf8 $receiptPath ($receipt|ConvertTo-Json -Depth 4);Move-Item -LiteralPath $staging -Destination $mountedPackage -ErrorAction Stop;$moved=$true;$receipt.State='MOUNTED';$receipt.MountedUtc=[DateTimeOffset]::UtcNow.ToString('o');Replace-Utf8Atomically $receiptPath ($receipt|ConvertTo-Json -Depth 4);[ordered]@{Status='PREPARED';BackupDirectory=$backup;ModsRoot=$modsRoot;MountedPackage=$mountedPackage}|ConvertTo-Json -Compress}
catch{if(Test-Path -LiteralPath $staging){Remove-Item -LiteralPath $staging -Recurse -Force};if($moved -and $backup -and(Test-Path -LiteralPath (Join-Path $backup 'metadata.json'))){& $PSCommandPath -Action Restore -SyntheticFixtureRoot $SyntheticFixtureRoot -BackupDirectory $backup|Out-Null};throw}
