[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$helper = Join-Path $PSScriptRoot 'Set-L00CF5AuthenticatedProfile.ps1'
$mountHelper = Join-Path $PSScriptRoot 'Set-L00CTestModMount.ps1'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ('isr-l00c-f5-fixture-' + [Guid]::NewGuid().ToString('N'))
function Assert-Refused([scriptblock]$Operation, [string]$Label) { try { & $Operation } catch { return }; throw "Expected refusal: $Label" }
function Test-StringArrayEqual([string[]]$Left, [string[]]$Right) {
    if ($Left.Count -ne $Right.Count) { return $false }
    for ($index = 0; $index -lt $Left.Count; $index++) { if ($Left[$index] -cne $Right[$index]) { return $false } }
    return $true
}
function Test-ByteArrayEqual([byte[]]$Left, [byte[]]$Right) {
    if ($Left.Length -ne $Right.Length) { return $false }
    for ($index = 0; $index -lt $Left.Length; $index++) { if ($Left[$index] -ne $Right[$index]) { return $false } }
    return $true
}
function Get-Sha256([byte[]]$Bytes) {
    $algorithm = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($algorithm.ComputeHash($Bytes))).Replace('-', '') }
    finally { $algorithm.Dispose() }
}
function Get-TreeHash([string]$Root) {
    $rows = foreach ($item in @(Get-ChildItem -LiteralPath $Root -File -Recurse | Sort-Object FullName)) { $relative = $item.FullName.Substring($Root.TrimEnd([IO.Path]::DirectorySeparatorChar).Length).TrimStart([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar); "$relative|$($item.Length)|$(Get-Sha256 ([IO.File]::ReadAllBytes($item.FullName)))" }
    Get-Sha256 ([Text.Encoding]::UTF8.GetBytes(($rows -join "`n")))
}
function New-Fixture([string]$Name, [string]$Arguments = '--tracelog --addModPath "$(ProjectDir)bin\$(Configuration)\Mods"', [string]$ActiveDebugProfile = 'Second profile must stay unchanged') {
    $root = Join-Path $temporaryRoot $Name; $properties = Join-Path $root 'src\WorldGen.VintageStory\Properties'; $mods = Join-Path $root 'src\WorldGen.VintageStory\bin\Debug\Mods'; $lab = Join-Path $root '.local\L00C'; $package = Join-Path $lab 'menu-action-testmod\Debug\isrworldgenl00clab'
    [void](New-Item -ItemType Directory -Path $properties -Force); [void](New-Item -ItemType Directory -Path $mods -Force); [void](New-Item -ItemType Directory -Path $package -Force)
    Set-Content -LiteralPath (Join-Path $lab '.isrworldgen-lab') -Value fixture -NoNewline; Set-Content -LiteralPath (Join-Path $package 'modinfo.json') -Value '{}' -NoNewline; Set-Content -LiteralPath (Join-Path $package 'ISRWorldGen.L00C.MenuActionLab.dll') -Value fixture -NoNewline
    $json = @'
{
  "profiles": {
    "ISRWorldGen Client (authenticated user data)": { "commandName": "Executable", "executablePath": "C:\\Game\\Vintagestory.exe", "commandLineArgs": "__ARGUMENTS__" },
    "Second profile must stay unchanged": { "commandName": "Executable", "executablePath": "C:\\Game\\Vintagestory.exe", "commandLineArgs": "--second" }
  }
}
'@.Replace('__ARGUMENTS__', $Arguments.Replace('\', '\\').Replace('"', '\"'))
    $launch = Join-Path $properties 'launchSettings.json'; [IO.File]::WriteAllText($launch, $json, [Text.UTF8Encoding]::new($false))
    $userSettings = Join-Path $root 'src\WorldGen.VintageStory\WorldGen.VintageStory.csproj.user'
    [IO.File]::WriteAllText($userSettings, ('<?xml version="1.0" encoding="utf-8"?><Project><PropertyGroup><ActiveDebugProfile>' + [Security.SecurityElement]::Escape($ActiveDebugProfile) + '</ActiveDebugProfile><UnrelatedSetting>preserve-me</UnrelatedSetting></PropertyGroup></Project>'), [Text.UTF8Encoding]::new($false))
    [pscustomobject]@{ Root = $root; Lab = $lab; Package = $package; Mods = $mods; Launch = $launch; UserSettings = $userSettings }
}
function Assert-ExternalWriteBlocked([string]$Path) {
    try { Add-Content -LiteralPath $Path -Value ' external mutation'; throw "Write was not blocked: $Path" }
    catch [IO.IOException] { return }
    finally { }
}
function Assert-ExternalReplaceBlocked([string]$Path) {
    $replacement = Join-Path ([IO.Path]::GetDirectoryName($Path)) ('.l00c-replace-' + [Guid]::NewGuid().ToString('N') + '.tmp')
    $backup = $replacement + '.backup'
    try {
        [IO.File]::WriteAllText($replacement, 'external replacement', [Text.UTF8Encoding]::new($false))
        try { [IO.File]::Replace($replacement, $Path, $backup, $true); throw "Replace was not blocked: $Path" }
        catch [IO.IOException] { return }
    }
    finally { foreach ($temporary in @($replacement, $backup)) { if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force } } }
}
function Assert-ExternalMutationBlocked([string]$Path) {
    Assert-ExternalWriteBlocked $Path; Assert-ExternalReplaceBlocked $Path
}
try {
    Assert-Refused { & $helper -Action Prepare -TestHook { } } 'non-synthetic test hook'
    $good = New-Fixture good; $before = [IO.File]::ReadAllBytes($good.Launch); $beforeUserSettings = [IO.File]::ReadAllBytes($good.UserSettings); $mountedPackage = Join-Path $good.Mods 'isrworldgenl00clab'
    if ([IO.Path]::GetFullPath((Join-Path $good.Mods 'isrworldgenl00clab')) -cne $mountedPackage -or -not (Test-Path -LiteralPath (Join-Path $good.Package 'modinfo.json') -PathType Leaf) -or -not (Test-Path -LiteralPath (Join-Path $good.Package 'ISRWorldGen.L00C.MenuActionLab.dll') -PathType Leaf)) { throw 'Fixture package must be a complete source package for the exact production Mods child.' }
    $beforeDocument = Get-Content -LiteralPath $good.Launch -Raw | ConvertFrom-Json
    $beforeTrailingProfiles = @($beforeDocument.profiles.PSObject.Properties | Select-Object -Skip 1 | ForEach-Object { $_.Name + ':' + ($_.Value | ConvertTo-Json -Depth 16 -Compress) })
    $receipt = & $helper -Action Prepare -SyntheticFixtureRoot $good.Root | ConvertFrom-Json
    $after = Get-Content -LiteralPath $good.Launch -Raw | ConvertFrom-Json
    $profiles = @($after.profiles.PSObject.Properties); $first = $profiles[0].Value; $second = $profiles[1].Value
    $preparedUserSettings = [Xml.XmlDocument]::new(); $preparedUserSettings.Load($good.UserSettings)
    $afterTrailingProfiles = @($after.profiles.PSObject.Properties | Select-Object -Skip 1 | ForEach-Object { $_.Name + ':' + ($_.Value | ConvertTo-Json -Depth 16 -Compress) })
    if (($first.commandLineArgs -split '--addModPath').Count -ne 2 -or $first.commandLineArgs -notmatch [regex]::Escape('--addModPath "$(ProjectDir)bin\$(Configuration)\Mods"') -or $first.commandLineArgs -match ('--addModPath "' + [regex]::Escape($good.Package) + '"') -or $first.commandLineArgs -match '(?i)--dataPath' -or $first.environmentVariables.ISR_L00C_LAB -ne '1' -or $first.environmentVariables.ISR_L00C_LAB_ROOT -ne $good.Lab -or $preparedUserSettings.SelectSingleNode("//*[local-name()='ActiveDebugProfile']").InnerText -ne 'ISRWorldGen Client (authenticated user data)' -or $preparedUserSettings.SelectSingleNode("//*[local-name()='UnrelatedSetting']").InnerText -ne 'preserve-me' -or -not (Test-Path -LiteralPath $mountedPackage -PathType Container) -or -not (Test-Path -LiteralPath (Join-Path $mountedPackage 'modinfo.json') -PathType Leaf) -or -not (Test-StringArrayEqual $beforeTrailingProfiles $afterTrailingProfiles)) { throw 'Prepare must select the verified first F5 profile, preserve unrelated user settings, and mount the lab package as its exact direct child.' }
    & $helper -Action Restore -SyntheticFixtureRoot $good.Root -BackupDirectory $receipt.BackupDirectory | Out-Null
    if (-not (Test-ByteArrayEqual $before ([IO.File]::ReadAllBytes($good.Launch))) -or -not (Test-ByteArrayEqual $beforeUserSettings ([IO.File]::ReadAllBytes($good.UserSettings))) -or (Test-Path -LiteralPath $mountedPackage)) { throw 'Restore did not reinstate strict original profile bytes and remove its mounted test package.' }
    # The runtime path is deliberately split: immediately after Debug.Start it
    # restores only the F5 settings, retaining the verified direct-child mount
    # until an explicit post-stop cleanup attestation is supplied.
    $split = New-Fixture split-transaction; $splitLaunch = [IO.File]::ReadAllBytes($split.Launch); $splitUser = [IO.File]::ReadAllBytes($split.UserSettings); $splitReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $split.Root | ConvertFrom-Json
    $splitRestore = & $helper -Action RestoreSettings -SyntheticFixtureRoot $split.Root -BackupDirectory $splitReceipt.BackupDirectory | ConvertFrom-Json
    if ($splitRestore.Status -ne 'SETTINGS_RESTORED' -or -not $splitRestore.MountRetained -or -not (Test-ByteArrayEqual $splitLaunch ([IO.File]::ReadAllBytes($split.Launch))) -or -not (Test-ByteArrayEqual $splitUser ([IO.File]::ReadAllBytes($split.UserSettings))) -or -not (Test-Path -LiteralPath (Join-Path $split.Mods 'isrworldgenl00clab'))) { throw 'RestoreSettings must restore both original setting files while retaining the verified mounted laboratory package.' }
    Assert-Refused { & $helper -Action CleanupMount -SyntheticFixtureRoot $split.Root -BackupDirectory $splitReceipt.BackupDirectory } 'cleanup without stopped-runtime attestation'
    if (-not (Test-Path -LiteralPath (Join-Path $split.Mods 'isrworldgenl00clab'))) { throw 'A refused cleanup must preserve the mounted laboratory package.' }
    $splitCleanup = & $helper -Action CleanupMount -RuntimeStopped -SyntheticFixtureRoot $split.Root -BackupDirectory $splitReceipt.BackupDirectory | ConvertFrom-Json
    if ($splitCleanup.Status -ne 'CLEANED' -or (Test-Path -LiteralPath (Join-Path $split.Mods 'isrworldgenl00clab'))) { throw 'CleanupMount must unmount only after explicit stopped-runtime attestation and completed settings phase.' }
    Assert-Refused { & $helper -Action CleanupMount -RuntimeStopped -SyntheticFixtureRoot $split.Root -BackupDirectory $splitReceipt.BackupDirectory } 'repeated cleanup phase'
    $splitTamper = New-Fixture split-cleanup-tamper; $splitTamperReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $splitTamper.Root | ConvertFrom-Json; & $helper -Action RestoreSettings -SyntheticFixtureRoot $splitTamper.Root -BackupDirectory $splitTamperReceipt.BackupDirectory | Out-Null; Add-Content -LiteralPath (Join-Path $splitTamper.Mods 'isrworldgenl00clab\modinfo.json') -Value 'tampered'; Assert-Refused { & $helper -Action CleanupMount -RuntimeStopped -SyntheticFixtureRoot $splitTamper.Root -BackupDirectory $splitTamperReceipt.BackupDirectory } 'tampered split cleanup'; if (-not (Test-Path -LiteralPath (Join-Path $splitTamper.Mods 'isrworldgenl00clab'))) { throw 'A provenance mismatch must preserve the mounted package for manual investigation.' }
    $prepareLaunchRace = New-Fixture prepare-launch-race; $prepareLaunchBefore = [IO.File]::ReadAllBytes($prepareLaunchRace.Launch); $prepareLaunchHook = { param($point) if ($point -eq 'PrepareBeforeLaunchSettingsWrite') { Assert-ExternalMutationBlocked $prepareLaunchRace.Launch } }; $prepareLaunchReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $prepareLaunchRace.Root -TestHook $prepareLaunchHook | ConvertFrom-Json; & $helper -Action Restore -SyntheticFixtureRoot $prepareLaunchRace.Root -BackupDirectory $prepareLaunchReceipt.BackupDirectory | Out-Null; if (-not (Test-ByteArrayEqual $prepareLaunchBefore ([IO.File]::ReadAllBytes($prepareLaunchRace.Launch)))) { throw 'Prepare launchSettings write lock did not preserve original bytes.' }
    $prepareUserRace = New-Fixture prepare-user-race; $prepareUserBefore = [IO.File]::ReadAllBytes($prepareUserRace.UserSettings); $prepareUserHook = { param($point) if ($point -eq 'PrepareBeforeUserSettingsWrite') { Assert-ExternalMutationBlocked $prepareUserRace.UserSettings } }; $prepareUserReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $prepareUserRace.Root -TestHook $prepareUserHook | ConvertFrom-Json; & $helper -Action Restore -SyntheticFixtureRoot $prepareUserRace.Root -BackupDirectory $prepareUserReceipt.BackupDirectory | Out-Null; if (-not (Test-ByteArrayEqual $prepareUserBefore ([IO.File]::ReadAllBytes($prepareUserRace.UserSettings)))) { throw 'Prepare user-settings write lock did not preserve original bytes.' }
    $restoreLaunchRace = New-Fixture restore-launch-race; $restoreLaunchBefore = [IO.File]::ReadAllBytes($restoreLaunchRace.Launch); $restoreLaunchReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $restoreLaunchRace.Root | ConvertFrom-Json; $restoreLaunchHook = { param($point) if ($point -eq 'RestoreBeforeLaunchSettingsWrite') { Assert-ExternalMutationBlocked $restoreLaunchRace.Launch } }; & $helper -Action Restore -SyntheticFixtureRoot $restoreLaunchRace.Root -BackupDirectory $restoreLaunchReceipt.BackupDirectory -TestHook $restoreLaunchHook | Out-Null; if (-not (Test-ByteArrayEqual $restoreLaunchBefore ([IO.File]::ReadAllBytes($restoreLaunchRace.Launch))) -or (Test-Path -LiteralPath (Join-Path $restoreLaunchRace.Mods 'isrworldgenl00clab'))) { throw 'Restore launchSettings write lock did not restore bytes before unmount.' }
    $restoreUserRace = New-Fixture restore-user-race; $restoreUserBefore = [IO.File]::ReadAllBytes($restoreUserRace.UserSettings); $restoreUserReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $restoreUserRace.Root | ConvertFrom-Json; $restoreUserHook = { param($point) if ($point -eq 'RestoreBeforeUserSettingsWrite') { Assert-ExternalMutationBlocked $restoreUserRace.UserSettings } }; & $helper -Action Restore -SyntheticFixtureRoot $restoreUserRace.Root -BackupDirectory $restoreUserReceipt.BackupDirectory -TestHook $restoreUserHook | Out-Null; if (-not (Test-ByteArrayEqual $restoreUserBefore ([IO.File]::ReadAllBytes($restoreUserRace.UserSettings))) -or (Test-Path -LiteralPath (Join-Path $restoreUserRace.Mods 'isrworldgenl00clab'))) { throw 'Restore user-settings write lock did not restore bytes before unmount.' }
    $restoreMountRace = New-Fixture restore-mount-race; $restoreMountReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $restoreMountRace.Root | ConvertFrom-Json; $restoreMountHook = { param($point) if ($point -eq 'RestoreBeforeMount') { Assert-ExternalMutationBlocked $restoreMountRace.Launch; Assert-ExternalMutationBlocked $restoreMountRace.UserSettings } }; & $helper -Action Restore -SyntheticFixtureRoot $restoreMountRace.Root -BackupDirectory $restoreMountReceipt.BackupDirectory -TestHook $restoreMountHook | Out-Null; if (Test-Path -LiteralPath (Join-Path $restoreMountRace.Mods 'isrworldgenl00clab')) { throw 'Restore must unmount only after both locked settings writes succeed.' }
    $truncateRecovery = New-Fixture truncate-recovery; $truncateLaunchBefore = [IO.File]::ReadAllBytes($truncateRecovery.Launch); $truncateUserBefore = [IO.File]::ReadAllBytes($truncateRecovery.UserSettings); $truncateHook = { param($point) if ($point -eq 'PrepareAfterLaunchSettingsTruncate') { throw 'simulated interrupted write' } }; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $truncateRecovery.Root -TestHook $truncateHook } 'prepare write interruption'; if (-not (Test-ByteArrayEqual $truncateLaunchBefore ([IO.File]::ReadAllBytes($truncateRecovery.Launch))) -or -not (Test-ByteArrayEqual $truncateUserBefore ([IO.File]::ReadAllBytes($truncateRecovery.UserSettings))) -or (Test-Path -LiteralPath (Join-Path $truncateRecovery.Mods 'isrworldgenl00clab'))) { throw 'Interrupted locked preparation must recover both durable original byte sequences and unmount.' }
    $truncatePrepareUser = New-Fixture truncate-prepare-user; $truncatePrepareUserLaunchBefore = [IO.File]::ReadAllBytes($truncatePrepareUser.Launch); $truncatePrepareUserBefore = [IO.File]::ReadAllBytes($truncatePrepareUser.UserSettings); $truncatePrepareUserHook = { param($point) if ($point -eq 'PrepareAfterUserSettingsTruncate') { throw 'simulated interrupted user write' } }; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $truncatePrepareUser.Root -TestHook $truncatePrepareUserHook } 'prepare user write interruption'; if (-not (Test-ByteArrayEqual $truncatePrepareUserLaunchBefore ([IO.File]::ReadAllBytes($truncatePrepareUser.Launch))) -or -not (Test-ByteArrayEqual $truncatePrepareUserBefore ([IO.File]::ReadAllBytes($truncatePrepareUser.UserSettings))) -or (Test-Path -LiteralPath (Join-Path $truncatePrepareUser.Mods 'isrworldgenl00clab'))) { throw 'Interrupted locked user preparation must recover both originals and unmount.' }
    $truncateRestoreUser = New-Fixture truncate-restore-user; $truncateRestoreUserReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $truncateRestoreUser.Root | ConvertFrom-Json; $truncateRestoreUserPreparedLaunch = [IO.File]::ReadAllBytes($truncateRestoreUser.Launch); $truncateRestoreUserPreparedUser = [IO.File]::ReadAllBytes($truncateRestoreUser.UserSettings); $truncateRestoreUserHook = { param($point) if ($point -eq 'RestoreAfterUserSettingsTruncate') { throw 'simulated interrupted user restore' } }; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $truncateRestoreUser.Root -BackupDirectory $truncateRestoreUserReceipt.BackupDirectory -TestHook $truncateRestoreUserHook } 'restore user write interruption'; if (-not (Test-ByteArrayEqual $truncateRestoreUserPreparedLaunch ([IO.File]::ReadAllBytes($truncateRestoreUser.Launch))) -or -not (Test-ByteArrayEqual $truncateRestoreUserPreparedUser ([IO.File]::ReadAllBytes($truncateRestoreUser.UserSettings))) -or -not (Test-Path -LiteralPath (Join-Path $truncateRestoreUser.Mods 'isrworldgenl00clab'))) { throw 'Interrupted locked user restore must recover prepared bytes and preserve the mount.' }
    $truncateRestoreLaunch = New-Fixture truncate-restore-launch; $truncateRestoreLaunchReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $truncateRestoreLaunch.Root | ConvertFrom-Json; $truncateRestoreLaunchPreparedLaunch = [IO.File]::ReadAllBytes($truncateRestoreLaunch.Launch); $truncateRestoreLaunchPreparedUser = [IO.File]::ReadAllBytes($truncateRestoreLaunch.UserSettings); $truncateRestoreLaunchHook = { param($point) if ($point -eq 'RestoreAfterLaunchSettingsTruncate') { throw 'simulated interrupted launch restore' } }; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $truncateRestoreLaunch.Root -BackupDirectory $truncateRestoreLaunchReceipt.BackupDirectory -TestHook $truncateRestoreLaunchHook } 'restore launch write interruption'; if (-not (Test-ByteArrayEqual $truncateRestoreLaunchPreparedLaunch ([IO.File]::ReadAllBytes($truncateRestoreLaunch.Launch))) -or -not (Test-ByteArrayEqual $truncateRestoreLaunchPreparedUser ([IO.File]::ReadAllBytes($truncateRestoreLaunch.UserSettings))) -or -not (Test-Path -LiteralPath (Join-Path $truncateRestoreLaunch.Mods 'isrworldgenl00clab'))) { throw 'Interrupted locked launch restore must recover prepared bytes and preserve the mount.' }
    $userTamper = New-Fixture user-tamper; $userTamperReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $userTamper.Root | ConvertFrom-Json; Add-Content -LiteralPath $userTamper.UserSettings -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $userTamper.Root -BackupDirectory $userTamperReceipt.BackupDirectory } 'user-settings modified hash'
    $userBackupTamper = New-Fixture user-backup-tamper; $userBackupReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $userBackupTamper.Root | ConvertFrom-Json; Add-Content -LiteralPath (Join-Path $userBackupReceipt.BackupDirectory 'WorldGen.VintageStory.csproj.user.original') -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $userBackupTamper.Root -BackupDirectory $userBackupReceipt.BackupDirectory } 'user-settings backup hash'
    foreach ($indicator in @('login', 'token', 'credential', 'password')) {
        $secret = New-Fixture ('secret-' + $indicator) ('--tracelog --' + $indicator + ' never-use')
        Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $secret.Root } "$indicator indicator"
    }
    $dataPath = New-Fixture datapath '--dataPath C:\\unsafe'; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $dataPath.Root } 'dataPath profile'
    $invalid = New-Fixture invalid; Remove-Item -LiteralPath (Join-Path $invalid.Package 'modinfo.json') -Force; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $invalid.Root } 'invalid package'
    $missingParent = New-Fixture missing-parent; Remove-Item -LiteralPath $missingParent.Mods -Force; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $missingParent.Root } 'missing existing production Mods parent'
    $collision = New-Fixture collision; [void](New-Item -ItemType Directory -Path (Join-Path $collision.Mods 'isrworldgenl00clab')); Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $collision.Root } 'existing production Mods child collision'
    $duplicateModPath = New-Fixture duplicate '--tracelog --addModPath "$(ProjectDir)bin\$(Configuration)\Mods" --addModPath "C:\ignored"'; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $duplicateModPath.Root } 'duplicate addModPath'
    $receiptFailure = New-Fixture receipt-failure; Assert-Refused { & $mountHelper -Action Prepare -SyntheticFixtureRoot $receiptFailure.Root -SimulateReceiptFailure } 'receipt persistence failure'; if (Test-Path -LiteralPath (Join-Path $receiptFailure.Mods 'isrworldgenl00clab')) { throw 'Receipt failure left an unreceipted mounted package.' }
    $race = New-Fixture race; [void](New-Item -ItemType Directory -Path (Join-Path $race.Mods 'isrworldgenl00clab')); Set-Content -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\modinfo.json') -Value '{}' -NoNewline; Set-Content -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\ISRWorldGen.L00C.MenuActionLab.dll') -Value fixture -NoNewline; Assert-Refused { & $mountHelper -Action Prepare -SyntheticFixtureRoot $race.Root } 'collision race simulation'; if (-not (Test-Path -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\modinfo.json'))) { throw 'Collision race simulation must retain the production child.' }
    $mountTamper = New-Fixture mount-tamper; $mountTamperReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountTamper.Root | ConvertFrom-Json; $mountTamperPath = Join-Path $mountTamper.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountTamperMarker = Get-Content -LiteralPath $mountTamperPath -Raw | ConvertFrom-Json; $mountTamperMarker.MountId = 'tampered-mount'; $mountTamperMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountTamperPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountTamper.Root -BackupDirectory $mountTamperReceipt.BackupDirectory } 'mount provenance tamper'
    $receiptTamper = New-Fixture receipt-tamper; $receiptTamperReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $receiptTamper.Root | ConvertFrom-Json; $mountMetadataPath = Join-Path $receiptTamperReceipt.BackupDirectory 'metadata.json'; $mountMetadata = Get-Content -LiteralPath $mountMetadataPath -Raw | ConvertFrom-Json; $mountMetadata.MountId = 'untrusted-mount'; $mountMetadata | ConvertTo-Json | Set-Content -LiteralPath $mountMetadataPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $receiptTamper.Root -BackupDirectory $receiptTamperReceipt.BackupDirectory } 'mount receipt tamper'
    $nullHash = New-Fixture null-hash; $nullHashReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $nullHash.Root | ConvertFrom-Json; $nullMarkerPath = Join-Path $nullHash.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $nullMarker = Get-Content -LiteralPath $nullMarkerPath -Raw | ConvertFrom-Json; $nullMarker.SourceTreeSha256 = $null; $nullMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $nullMarkerPath -NoNewline; $nullMetadataPath = Join-Path $nullHashReceipt.BackupDirectory 'metadata.json'; $nullMetadata = Get-Content -LiteralPath $nullMetadataPath -Raw | ConvertFrom-Json; $nullMetadata.SourceTreeSha256 = $null; $nullMetadata.MountedTreeSha256 = Get-TreeHash (Join-Path $nullHash.Mods 'isrworldgenl00clab'); $nullMetadata | ConvertTo-Json | Set-Content -LiteralPath $nullMetadataPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $nullHash.Root -BackupDirectory $nullHashReceipt.BackupDirectory } 'null receipt and marker source hash'; if (-not (Test-Path -LiteralPath (Join-Path $nullHash.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Null source hashes must preserve the mounted child.' }
    $mountedHashTamper = New-Fixture mounted-hash-tamper; $mountedHashReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountedHashTamper.Root | ConvertFrom-Json; $mountedMarkerPath = Join-Path $mountedHashTamper.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountedMarker = Get-Content -LiteralPath $mountedMarkerPath -Raw | ConvertFrom-Json; $mountedMarker.MountedTreeSha256 = $null; $mountedMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountedMarkerPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountedHashTamper.Root -BackupDirectory $mountedHashReceipt.BackupDirectory } 'null marker mounted tree hash'; if (-not (Test-Path -LiteralPath (Join-Path $mountedHashTamper.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Null mounted tree hash must preserve the mounted child.' }
    $mountedMismatch = New-Fixture mounted-mismatch; $mountedMismatchReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountedMismatch.Root | ConvertFrom-Json; $mountedMismatchPath = Join-Path $mountedMismatch.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountedMismatchMarker = Get-Content -LiteralPath $mountedMismatchPath -Raw | ConvertFrom-Json; $mountedMismatchMarker.MountedTreeSha256 = ('A' * 64); $mountedMismatchMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountedMismatchPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountedMismatch.Root -BackupDirectory $mountedMismatchReceipt.BackupDirectory } 'valid marker mounted tree mismatch'; if (-not (Test-Path -LiteralPath (Join-Path $mountedMismatch.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Mismatched mounted tree hash must preserve the mounted child.' }
    $bothHashes = New-Fixture both-hashes; $bothHashesReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $bothHashes.Root | ConvertFrom-Json; $bothMarkerPath = Join-Path $bothHashes.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $bothMarker = Get-Content -LiteralPath $bothMarkerPath -Raw | ConvertFrom-Json; $bothMarker.SourceTreeSha256 = ('B' * 64); $bothMarker.MountedTreeSha256 = ('B' * 64); $bothMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $bothMarkerPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $bothHashes.Root -BackupDirectory $bothHashesReceipt.BackupDirectory } 'both marker tree hashes mismatch'; if (-not (Test-Path -LiteralPath (Join-Path $bothHashes.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Both mismatched hashes must preserve the mounted child.' }
    $orderedRestore = New-Fixture ordered-restore; $orderedLaunchBefore = [IO.File]::ReadAllBytes($orderedRestore.Launch); $orderedUserBefore = [IO.File]::ReadAllBytes($orderedRestore.UserSettings); $orderedReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $orderedRestore.Root | ConvertFrom-Json; $orderedMarkerPath = Join-Path $orderedRestore.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $orderedMarker = Get-Content -LiteralPath $orderedMarkerPath -Raw | ConvertFrom-Json; $orderedMarker.MountId = 'tampered-mount'; $orderedMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $orderedMarkerPath -NoNewline; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $orderedRestore.Root -BackupDirectory $orderedReceipt.BackupDirectory } 'tampered mount after profile restore'; if (-not (Test-ByteArrayEqual $orderedLaunchBefore ([IO.File]::ReadAllBytes($orderedRestore.Launch))) -or -not (Test-ByteArrayEqual $orderedUserBefore ([IO.File]::ReadAllBytes($orderedRestore.UserSettings))) -or -not (Test-Path -LiteralPath (Join-Path $orderedRestore.Mods 'isrworldgenl00clab'))) { throw 'Tampered mount must preserve the mount while both settings restores complete first.' }
    $tamper = New-Fixture tamper; $tamperReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $tamper.Root | ConvertFrom-Json; Add-Content -LiteralPath $tamper.Launch -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $tamper.Root -BackupDirectory $tamperReceipt.BackupDirectory } 'modified hash'
    $owned = New-Fixture owner; $ownerReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $owned.Root | ConvertFrom-Json
    $ownerReceiptPath = Join-Path $ownerReceipt.BackupDirectory 'metadata.json'; $ownerMetadata = Get-Content -LiteralPath $ownerReceiptPath -Raw | ConvertFrom-Json; $ownerMetadata.Owner = 'untrusted-owner'; $ownerMetadata | ConvertTo-Json | Set-Content -LiteralPath $ownerReceiptPath -NoNewline
    Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $owned.Root -BackupDirectory $ownerReceipt.BackupDirectory } 'backup owner'
    $metadataTamper = New-Fixture metadata-tamper; $metadataReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $metadataTamper.Root | ConvertFrom-Json
    $metadataPath = Join-Path $metadataReceipt.BackupDirectory 'metadata.json'; $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json; $metadata.OriginalSha256 = '0000000000000000000000000000000000000000000000000000000000000000'; $metadata | ConvertTo-Json | Set-Content -LiteralPath $metadataPath -NoNewline
    Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $metadataTamper.Root -BackupDirectory $metadataReceipt.BackupDirectory } 'receipt hash inconsistency'
    $originalTamper = New-Fixture original-tamper; $originalReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $originalTamper.Root | ConvertFrom-Json
    Add-Content -LiteralPath (Join-Path $originalReceipt.BackupDirectory 'launchSettings.original.json') -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $originalTamper.Root -BackupDirectory $originalReceipt.BackupDirectory } 'backup original hash'
    [ordered]@{ TestId = 'L00-C-F5-AUTHENTICATED-PROFILE'; Status = 'PASS'; Scope = 'Synthetic launchSettings fixtures only; no real profile, login, token, or client process was used.' } | ConvertTo-Json -Compress
} finally { if (Test-Path -LiteralPath $temporaryRoot) { Remove-Item -LiteralPath $temporaryRoot -Recurse -Force } }
