[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$helper = Join-Path $PSScriptRoot 'Set-L00CF5AuthenticatedProfile.ps1'
$mountHelper = Join-Path $PSScriptRoot 'Set-L00CTestModMount.ps1'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ('isr-l00c-f5-fixture-' + [Guid]::NewGuid().ToString('N'))
function Assert-Refused([scriptblock]$Operation, [string]$Label) { try { & $Operation } catch { return }; throw "Expected refusal: $Label" }
function Test-StringArrayEqual([string[]]$Left, [string[]]$Right) {
    if ($Left.Count -ne $Right.Count) { return $false }
    for ($index = 0; $index -lt $Left.Count; $index++) { if ($Left[$index] -cne $Right[$index]) { return $false } }
    return $true
}
function Test-ByteArrayEqual([byte[]]$Left, [byte[]]$Right) {
    if ($Left.Length -ne $Right.Length) { return $false }
    for ($index = 0; $index -lt $Left.Length; $index++) { if ($Left[$index] -ne $Right[$index]) { return $false } }
    return $true
}
function Get-TreeHash([string]$Root) {
    $rows = foreach ($item in @(Get-ChildItem -LiteralPath $Root -File -Recurse | Sort-Object FullName)) { $relative = $item.FullName.Substring($Root.TrimEnd([IO.Path]::DirectorySeparatorChar).Length).TrimStart([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar); "$relative|$($item.Length)|$([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([IO.File]::ReadAllBytes($item.FullName))))" }
    [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes(($rows -join "`n"))))
}
function New-Fixture([string]$Name, [string]$Arguments = '--tracelog --addModPath "$(ProjectDir)bin\$(Configuration)\Mods"') {
    $root = Join-Path $temporaryRoot $Name; $properties = Join-Path $root 'src\WorldGen.VintageStory\Properties'; $mods = Join-Path $root 'src\WorldGen.VintageStory\bin\Debug\Mods'; $lab = Join-Path $root '.local\L00C'; $package = Join-Path $lab 'menu-action-testmod\Debug\isrworldgenl00clab'
    [void](New-Item -ItemType Directory -Path $properties -Force); [void](New-Item -ItemType Directory -Path $mods -Force); [void](New-Item -ItemType Directory -Path $package -Force)
    Set-Content -LiteralPath (Join-Path $lab '.isrworldgen-lab') -Value fixture -NoNewline; Set-Content -LiteralPath (Join-Path $package 'modinfo.json') -Value '{}' -NoNewline; Set-Content -LiteralPath (Join-Path $package 'ISRWorldGen.L00C.MenuActionLab.dll') -Value fixture -NoNewline
    $json = @'
{
  "profiles": {
    "ISRWorldGen Client (authenticated user data)": { "commandName": "Executable", "executablePath": "C:\\Game\\Vintagestory.exe", "commandLineArgs": "__ARGUMENTS__" },
    "Second profile must stay unchanged": { "commandName": "Executable", "executablePath": "C:\\Game\\Vintagestory.exe", "commandLineArgs": "--second" }
  }
}
'@.Replace('__ARGUMENTS__', $Arguments.Replace('\', '\\').Replace('"', '\"'))
    $launch = Join-Path $properties 'launchSettings.json'; [IO.File]::WriteAllText($launch, $json, [Text.UTF8Encoding]::new($false)); [pscustomobject]@{ Root = $root; Lab = $lab; Package = $package; Mods = $mods; Launch = $launch }
}
try {
    $good = New-Fixture good; $before = [IO.File]::ReadAllBytes($good.Launch); $mountedPackage = Join-Path $good.Mods 'isrworldgenl00clab'
    if ([IO.Path]::GetFullPath((Join-Path $good.Mods 'isrworldgenl00clab')) -cne $mountedPackage -or -not (Test-Path -LiteralPath (Join-Path $good.Package 'modinfo.json') -PathType Leaf) -or -not (Test-Path -LiteralPath (Join-Path $good.Package 'ISRWorldGen.L00C.MenuActionLab.dll') -PathType Leaf)) { throw 'Fixture package must be a complete source package for the exact production Mods child.' }
    $beforeDocument = Get-Content -LiteralPath $good.Launch -Raw | ConvertFrom-Json
    $beforeTrailingProfiles = @($beforeDocument.profiles.PSObject.Properties | Select-Object -Skip 1 | ForEach-Object { $_.Name + ':' + ($_.Value | ConvertTo-Json -Depth 16 -Compress) })
    $receipt = & $helper -Action Prepare -SyntheticFixtureRoot $good.Root | ConvertFrom-Json
    $after = Get-Content -LiteralPath $good.Launch -Raw | ConvertFrom-Json
    $profiles = @($after.profiles.PSObject.Properties); $first = $profiles[0].Value; $second = $profiles[1].Value
    $afterTrailingProfiles = @($after.profiles.PSObject.Properties | Select-Object -Skip 1 | ForEach-Object { $_.Name + ':' + ($_.Value | ConvertTo-Json -Depth 16 -Compress) })
    if (($first.commandLineArgs -split '--addModPath').Count -ne 2 -or $first.commandLineArgs -notmatch [regex]::Escape('--addModPath "$(ProjectDir)bin\$(Configuration)\Mods"') -or $first.commandLineArgs -match ('--addModPath "' + [regex]::Escape($good.Package) + '"') -or $first.commandLineArgs -match '(?i)--dataPath' -or $first.environmentVariables.ISR_L00C_LAB -ne '1' -or $first.environmentVariables.ISR_L00C_LAB_ROOT -ne $good.Lab -or -not (Test-Path -LiteralPath $mountedPackage -PathType Container) -or -not (Test-Path -LiteralPath (Join-Path $mountedPackage 'modinfo.json') -PathType Leaf) -or -not (Test-StringArrayEqual $beforeTrailingProfiles $afterTrailingProfiles)) { throw 'Prepare must preserve the sole production Mods addModPath and mount the lab package as its exact direct child.' }
    & $helper -Action Restore -SyntheticFixtureRoot $good.Root -BackupDirectory $receipt.BackupDirectory | Out-Null
    if (-not (Test-ByteArrayEqual $before ([IO.File]::ReadAllBytes($good.Launch))) -or (Test-Path -LiteralPath $mountedPackage)) { throw 'Restore did not reinstate strict original bytes and remove its mounted test package.' }
    foreach ($indicator in @('login', 'token', 'credential', 'password')) {
        $secret = New-Fixture ('secret-' + $indicator) ('--tracelog --' + $indicator + ' never-use')
        Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $secret.Root } "$indicator indicator"
    }
    $dataPath = New-Fixture datapath '--dataPath C:\\unsafe'; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $dataPath.Root } 'dataPath profile'
    $invalid = New-Fixture invalid; Remove-Item -LiteralPath (Join-Path $invalid.Package 'modinfo.json') -Force; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $invalid.Root } 'invalid package'
    $missingParent = New-Fixture missing-parent; Remove-Item -LiteralPath $missingParent.Mods -Force; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $missingParent.Root } 'missing existing production Mods parent'
    $collision = New-Fixture collision; [void](New-Item -ItemType Directory -Path (Join-Path $collision.Mods 'isrworldgenl00clab')); Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $collision.Root } 'existing production Mods child collision'
    $duplicateModPath = New-Fixture duplicate '--tracelog --addModPath "$(ProjectDir)bin\$(Configuration)\Mods" --addModPath "C:\ignored"'; Assert-Refused { & $helper -Action Prepare -SyntheticFixtureRoot $duplicateModPath.Root } 'duplicate addModPath'
    $receiptFailure = New-Fixture receipt-failure; Assert-Refused { & $mountHelper -Action Prepare -SyntheticFixtureRoot $receiptFailure.Root -SimulateReceiptFailure } 'receipt persistence failure'; if (Test-Path -LiteralPath (Join-Path $receiptFailure.Mods 'isrworldgenl00clab')) { throw 'Receipt failure left an unreceipted mounted package.' }
    $race = New-Fixture race; [void](New-Item -ItemType Directory -Path (Join-Path $race.Mods 'isrworldgenl00clab')); Set-Content -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\modinfo.json') -Value '{}' -NoNewline; Set-Content -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\ISRWorldGen.L00C.MenuActionLab.dll') -Value fixture -NoNewline; Assert-Refused { & $mountHelper -Action Prepare -SyntheticFixtureRoot $race.Root } 'collision race simulation'; if (-not (Test-Path -LiteralPath (Join-Path $race.Mods 'isrworldgenl00clab\modinfo.json'))) { throw 'Collision race simulation must retain the production child.' }
    $mountTamper = New-Fixture mount-tamper; $mountTamperReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountTamper.Root | ConvertFrom-Json; $mountTamperPath = Join-Path $mountTamper.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountTamperMarker = Get-Content -LiteralPath $mountTamperPath -Raw | ConvertFrom-Json; $mountTamperMarker.MountId = 'tampered-mount'; $mountTamperMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountTamperPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountTamper.Root -BackupDirectory $mountTamperReceipt.BackupDirectory } 'mount provenance tamper'
    $receiptTamper = New-Fixture receipt-tamper; $receiptTamperReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $receiptTamper.Root | ConvertFrom-Json; $mountMetadataPath = Join-Path $receiptTamperReceipt.BackupDirectory 'metadata.json'; $mountMetadata = Get-Content -LiteralPath $mountMetadataPath -Raw | ConvertFrom-Json; $mountMetadata.MountId = 'untrusted-mount'; $mountMetadata | ConvertTo-Json | Set-Content -LiteralPath $mountMetadataPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $receiptTamper.Root -BackupDirectory $receiptTamperReceipt.BackupDirectory } 'mount receipt tamper'
    $nullHash = New-Fixture null-hash; $nullHashReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $nullHash.Root | ConvertFrom-Json; $nullMarkerPath = Join-Path $nullHash.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $nullMarker = Get-Content -LiteralPath $nullMarkerPath -Raw | ConvertFrom-Json; $nullMarker.SourceTreeSha256 = $null; $nullMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $nullMarkerPath -NoNewline; $nullMetadataPath = Join-Path $nullHashReceipt.BackupDirectory 'metadata.json'; $nullMetadata = Get-Content -LiteralPath $nullMetadataPath -Raw | ConvertFrom-Json; $nullMetadata.SourceTreeSha256 = $null; $nullMetadata.MountedTreeSha256 = Get-TreeHash (Join-Path $nullHash.Mods 'isrworldgenl00clab'); $nullMetadata | ConvertTo-Json | Set-Content -LiteralPath $nullMetadataPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $nullHash.Root -BackupDirectory $nullHashReceipt.BackupDirectory } 'null receipt and marker source hash'; if (-not (Test-Path -LiteralPath (Join-Path $nullHash.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Null source hashes must preserve the mounted child.' }
    $mountedHashTamper = New-Fixture mounted-hash-tamper; $mountedHashReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountedHashTamper.Root | ConvertFrom-Json; $mountedMarkerPath = Join-Path $mountedHashTamper.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountedMarker = Get-Content -LiteralPath $mountedMarkerPath -Raw | ConvertFrom-Json; $mountedMarker.MountedTreeSha256 = $null; $mountedMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountedMarkerPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountedHashTamper.Root -BackupDirectory $mountedHashReceipt.BackupDirectory } 'null marker mounted tree hash'; if (-not (Test-Path -LiteralPath (Join-Path $mountedHashTamper.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Null mounted tree hash must preserve the mounted child.' }
    $mountedMismatch = New-Fixture mounted-mismatch; $mountedMismatchReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $mountedMismatch.Root | ConvertFrom-Json; $mountedMismatchPath = Join-Path $mountedMismatch.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $mountedMismatchMarker = Get-Content -LiteralPath $mountedMismatchPath -Raw | ConvertFrom-Json; $mountedMismatchMarker.MountedTreeSha256 = ('A' * 64); $mountedMismatchMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $mountedMismatchPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $mountedMismatch.Root -BackupDirectory $mountedMismatchReceipt.BackupDirectory } 'valid marker mounted tree mismatch'; if (-not (Test-Path -LiteralPath (Join-Path $mountedMismatch.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Mismatched mounted tree hash must preserve the mounted child.' }
    $bothHashes = New-Fixture both-hashes; $bothHashesReceipt = & $mountHelper -Action Prepare -SyntheticFixtureRoot $bothHashes.Root | ConvertFrom-Json; $bothMarkerPath = Join-Path $bothHashes.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $bothMarker = Get-Content -LiteralPath $bothMarkerPath -Raw | ConvertFrom-Json; $bothMarker.SourceTreeSha256 = ('B' * 64); $bothMarker.MountedTreeSha256 = ('B' * 64); $bothMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $bothMarkerPath -NoNewline; Assert-Refused { & $mountHelper -Action Restore -SyntheticFixtureRoot $bothHashes.Root -BackupDirectory $bothHashesReceipt.BackupDirectory } 'both marker tree hashes mismatch'; if (-not (Test-Path -LiteralPath (Join-Path $bothHashes.Mods 'isrworldgenl00clab') -PathType Container)) { throw 'Both mismatched hashes must preserve the mounted child.' }
    $orderedRestore = New-Fixture ordered-restore; $orderedReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $orderedRestore.Root | ConvertFrom-Json; $orderedPrepared = [IO.File]::ReadAllBytes($orderedRestore.Launch); $orderedMarkerPath = Join-Path $orderedRestore.Mods 'isrworldgenl00clab\.isrworldgen-l00c-mount.json'; $orderedMarker = Get-Content -LiteralPath $orderedMarkerPath -Raw | ConvertFrom-Json; $orderedMarker.MountId = 'tampered-mount'; $orderedMarker | ConvertTo-Json -Compress | Set-Content -LiteralPath $orderedMarkerPath -NoNewline; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $orderedRestore.Root -BackupDirectory $orderedReceipt.BackupDirectory } 'tampered mount before profile restore'; if (-not (Test-ByteArrayEqual $orderedPrepared ([IO.File]::ReadAllBytes($orderedRestore.Launch)))) { throw 'Tampered mount must not partially restore launchSettings.json.' }
    $tamper = New-Fixture tamper; $tamperReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $tamper.Root | ConvertFrom-Json; Add-Content -LiteralPath $tamper.Launch -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $tamper.Root -BackupDirectory $tamperReceipt.BackupDirectory } 'modified hash'
    $owned = New-Fixture owner; $ownerReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $owned.Root | ConvertFrom-Json
    $ownerReceiptPath = Join-Path $ownerReceipt.BackupDirectory 'metadata.json'; $ownerMetadata = Get-Content -LiteralPath $ownerReceiptPath -Raw | ConvertFrom-Json; $ownerMetadata.Owner = 'untrusted-owner'; $ownerMetadata | ConvertTo-Json | Set-Content -LiteralPath $ownerReceiptPath -NoNewline
    Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $owned.Root -BackupDirectory $ownerReceipt.BackupDirectory } 'backup owner'
    $metadataTamper = New-Fixture metadata-tamper; $metadataReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $metadataTamper.Root | ConvertFrom-Json
    $metadataPath = Join-Path $metadataReceipt.BackupDirectory 'metadata.json'; $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json; $metadata.OriginalSha256 = '0000000000000000000000000000000000000000000000000000000000000000'; $metadata | ConvertTo-Json | Set-Content -LiteralPath $metadataPath -NoNewline
    Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $metadataTamper.Root -BackupDirectory $metadataReceipt.BackupDirectory } 'receipt hash inconsistency'
    $originalTamper = New-Fixture original-tamper; $originalReceipt = & $helper -Action Prepare -SyntheticFixtureRoot $originalTamper.Root | ConvertFrom-Json
    Add-Content -LiteralPath (Join-Path $originalReceipt.BackupDirectory 'launchSettings.original.json') -Value ' '; Assert-Refused { & $helper -Action Restore -SyntheticFixtureRoot $originalTamper.Root -BackupDirectory $originalReceipt.BackupDirectory } 'backup original hash'
    [ordered]@{ TestId = 'L00-C-F5-AUTHENTICATED-PROFILE'; Status = 'PASS'; Scope = 'Synthetic launchSettings fixtures only; no real profile, login, token, or client process was used.' } | ConvertTo-Json -Compress
} finally { if (Test-Path -LiteralPath $temporaryRoot) { Remove-Item -LiteralPath $temporaryRoot -Recurse -Force } }
