<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/bin/**;**/obj/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/WorldGen.Core/WorldGen.Core.csproj" /></ItemGroup>
</Project>
