<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ISRWorldGen.Tools</AssemblyName>
    <RootNamespace>ISRWorldGen.Tools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldGen.Core\WorldGen.Core.csproj" />
  </ItemGroup>
</Project>
